/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ProfileRegistry__factory } from "./ProfileRegistry__factory";
export { RewardToken__factory } from "./RewardToken__factory";
export { Verification__factory } from "./Verification__factory";
