packages:
  - backend
  - apps/web
  - apps/mobile
  - contracts
  - subgraph
  - shared

ignoredBuiltDependencies:
  - '@reown/appkit'
  - better-sqlite3
  - esbuild
  - keccak
  - protobufjs
  - secp256k1
