/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace CommunityVoting {
  export type SettlementStruct = {
    poster: AddressLike;
    isEco: boolean;
    mlConfidencePct: BigNumberish;
    communityWeightPct: BigNumberish;
    posterReward: BigNumberish;
    totalVoterPool: BigNumberish;
    voterMerkleRoot: BytesLike;
    settledAt: BigNumberish;
    settled: boolean;
  };

  export type SettlementStructOutput = [
    poster: string,
    isEco: boolean,
    mlConfidencePct: bigint,
    communityWeightPct: bigint,
    posterReward: bigint,
    totalVoterPool: bigint,
    voterMerkleRoot: string,
    settledAt: bigint,
    settled: boolean
  ] & {
    poster: string;
    isEco: boolean;
    mlConfidencePct: bigint;
    communityWeightPct: bigint;
    posterReward: bigint;
    totalVoterPool: bigint;
    voterMerkleRoot: string;
    settledAt: bigint;
    settled: boolean;
  };
}

export interface CommunityVotingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BASE_REWARD"
      | "VOTER_REWARD_PERCENT"
      | "claimVoterReward"
      | "getReputation"
      | "getSettlement"
      | "hasClaimed"
      | "isSettled"
      | "owner"
      | "renounceOwnership"
      | "reputation"
      | "rewardToken"
      | "settlePost"
      | "settlements"
      | "transferOwnership"
      | "updateReputation"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "PostSettled"
      | "ReputationUpdated"
      | "VoterRewardClaimed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BASE_REWARD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VOTER_REWARD_PERCENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimVoterReward",
    values: [string, BigNumberish, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getReputation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSettlement",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "hasClaimed",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "isSettled", values: [string]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reputation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rewardToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "settlePost",
    values: [
      string,
      AddressLike,
      boolean,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "settlements",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateReputation",
    values: [AddressLike[], boolean[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "BASE_REWARD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VOTER_REWARD_PERCENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimVoterReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSettlement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasClaimed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isSettled", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reputation", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rewardToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "settlePost", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "settlements",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateReputation",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PostSettledEvent {
  export type InputTuple = [
    postCidHash: BytesLike,
    postCid: string,
    poster: AddressLike,
    isEco: boolean,
    posterReward: BigNumberish,
    voterPool: BigNumberish,
    merkleRoot: BytesLike
  ];
  export type OutputTuple = [
    postCidHash: string,
    postCid: string,
    poster: string,
    isEco: boolean,
    posterReward: bigint,
    voterPool: bigint,
    merkleRoot: string
  ];
  export interface OutputObject {
    postCidHash: string;
    postCid: string;
    poster: string;
    isEco: boolean;
    posterReward: bigint;
    voterPool: bigint;
    merkleRoot: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReputationUpdatedEvent {
  export type InputTuple = [
    user: AddressLike,
    newReputation: BigNumberish,
    wasCorrect: boolean
  ];
  export type OutputTuple = [
    user: string,
    newReputation: bigint,
    wasCorrect: boolean
  ];
  export interface OutputObject {
    user: string;
    newReputation: bigint;
    wasCorrect: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoterRewardClaimedEvent {
  export type InputTuple = [
    postCidHash: BytesLike,
    voter: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    postCidHash: string,
    voter: string,
    amount: bigint
  ];
  export interface OutputObject {
    postCidHash: string;
    voter: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CommunityVoting extends BaseContract {
  connect(runner?: ContractRunner | null): CommunityVoting;
  waitForDeployment(): Promise<this>;

  interface: CommunityVotingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BASE_REWARD: TypedContractMethod<[], [bigint], "view">;

  VOTER_REWARD_PERCENT: TypedContractMethod<[], [bigint], "view">;

  claimVoterReward: TypedContractMethod<
    [postCid: string, voterShare: BigNumberish, proof: BytesLike[]],
    [void],
    "nonpayable"
  >;

  getReputation: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getSettlement: TypedContractMethod<
    [postCid: string],
    [CommunityVoting.SettlementStructOutput],
    "view"
  >;

  hasClaimed: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  isSettled: TypedContractMethod<[postCid: string], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  reputation: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  rewardToken: TypedContractMethod<[], [string], "view">;

  settlePost: TypedContractMethod<
    [
      postCid: string,
      poster: AddressLike,
      isEco: boolean,
      mlConfidencePct: BigNumberish,
      communityWeightPct: BigNumberish,
      voterMerkleRoot: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  settlements: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        boolean
      ] & {
        poster: string;
        isEco: boolean;
        mlConfidencePct: bigint;
        communityWeightPct: bigint;
        posterReward: bigint;
        totalVoterPool: bigint;
        voterMerkleRoot: string;
        settledAt: bigint;
        settled: boolean;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateReputation: TypedContractMethod<
    [voters: AddressLike[], wasCorrect: boolean[]],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BASE_REWARD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VOTER_REWARD_PERCENT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "claimVoterReward"
  ): TypedContractMethod<
    [postCid: string, voterShare: BigNumberish, proof: BytesLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getReputation"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSettlement"
  ): TypedContractMethod<
    [postCid: string],
    [CommunityVoting.SettlementStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasClaimed"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isSettled"
  ): TypedContractMethod<[postCid: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reputation"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "rewardToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "settlePost"
  ): TypedContractMethod<
    [
      postCid: string,
      poster: AddressLike,
      isEco: boolean,
      mlConfidencePct: BigNumberish,
      communityWeightPct: BigNumberish,
      voterMerkleRoot: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "settlements"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        boolean
      ] & {
        poster: string;
        isEco: boolean;
        mlConfidencePct: bigint;
        communityWeightPct: bigint;
        posterReward: bigint;
        totalVoterPool: bigint;
        voterMerkleRoot: string;
        settledAt: bigint;
        settled: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateReputation"
  ): TypedContractMethod<
    [voters: AddressLike[], wasCorrect: boolean[]],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PostSettled"
  ): TypedContractEvent<
    PostSettledEvent.InputTuple,
    PostSettledEvent.OutputTuple,
    PostSettledEvent.OutputObject
  >;
  getEvent(
    key: "ReputationUpdated"
  ): TypedContractEvent<
    ReputationUpdatedEvent.InputTuple,
    ReputationUpdatedEvent.OutputTuple,
    ReputationUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "VoterRewardClaimed"
  ): TypedContractEvent<
    VoterRewardClaimedEvent.InputTuple,
    VoterRewardClaimedEvent.OutputTuple,
    VoterRewardClaimedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PostSettled(bytes32,string,address,bool,uint256,uint256,bytes32)": TypedContractEvent<
      PostSettledEvent.InputTuple,
      PostSettledEvent.OutputTuple,
      PostSettledEvent.OutputObject
    >;
    PostSettled: TypedContractEvent<
      PostSettledEvent.InputTuple,
      PostSettledEvent.OutputTuple,
      PostSettledEvent.OutputObject
    >;

    "ReputationUpdated(address,int256,bool)": TypedContractEvent<
      ReputationUpdatedEvent.InputTuple,
      ReputationUpdatedEvent.OutputTuple,
      ReputationUpdatedEvent.OutputObject
    >;
    ReputationUpdated: TypedContractEvent<
      ReputationUpdatedEvent.InputTuple,
      ReputationUpdatedEvent.OutputTuple,
      ReputationUpdatedEvent.OutputObject
    >;

    "VoterRewardClaimed(bytes32,address,uint256)": TypedContractEvent<
      VoterRewardClaimedEvent.InputTuple,
      VoterRewardClaimedEvent.OutputTuple,
      VoterRewardClaimedEvent.OutputObject
    >;
    VoterRewardClaimed: TypedContractEvent<
      VoterRewardClaimedEvent.InputTuple,
      VoterRewardClaimedEvent.OutputTuple,
      VoterRewardClaimedEvent.OutputObject
    >;
  };
}
