/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace DynamicVerification {
  export type PostRewardStruct = {
    author: AddressLike;
    baseRewardMinted: BigNumberish;
    bonusRewardMinted: BigNumberish;
    verifiedAt: BigNumberish;
    bonusClaimedAt: BigNumberish;
    verified: boolean;
    bonusClaimed: boolean;
  };

  export type PostRewardStructOutput = [
    author: string,
    baseRewardMinted: bigint,
    bonusRewardMinted: bigint,
    verifiedAt: bigint,
    bonusClaimedAt: bigint,
    verified: boolean,
    bonusClaimed: boolean
  ] & {
    author: string;
    baseRewardMinted: bigint;
    bonusRewardMinted: bigint;
    verifiedAt: bigint;
    bonusClaimedAt: bigint;
    verified: boolean;
    bonusClaimed: boolean;
  };
}

export interface DynamicVerificationInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BASE_REWARD"
      | "COMMENT_WEIGHT"
      | "COOLDOWN_PERIOD"
      | "ENGAGEMENT_TYPEHASH"
      | "ENGAGEMENT_WINDOW"
      | "LIKE_WEIGHT"
      | "MAX_BONUS_MULTIPLIER"
      | "MAX_REP_BONUS_PCT"
      | "MIN_CONFIDENCE"
      | "SHARE_WEIGHT"
      | "VERDICT_TYPEHASH"
      | "VIEW_WEIGHT"
      | "addVerifier"
      | "authorizedVerifiers"
      | "batchSetUserLevels"
      | "claimEngagementBonus"
      | "eip712Domain"
      | "getPostReward"
      | "lastRewardTime"
      | "owner"
      | "postRewards"
      | "removeVerifier"
      | "renounceOwnership"
      | "rewardToken"
      | "setUserLevel"
      | "transferOwnership"
      | "usedNonces"
      | "userLevel"
      | "verifyAndReward"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BonusRewardMinted"
      | "EIP712DomainChanged"
      | "OwnershipTransferred"
      | "PostVerified"
      | "VerifierAdded"
      | "VerifierRemoved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BASE_REWARD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "COMMENT_WEIGHT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "COOLDOWN_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ENGAGEMENT_TYPEHASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ENGAGEMENT_WINDOW",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LIKE_WEIGHT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_BONUS_MULTIPLIER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_REP_BONUS_PCT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_CONFIDENCE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SHARE_WEIGHT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VERDICT_TYPEHASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VIEW_WEIGHT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addVerifier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedVerifiers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "batchSetUserLevels",
    values: [AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "claimEngagementBonus",
    values: [
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "eip712Domain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPostReward",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "lastRewardTime",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "postRewards",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeVerifier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rewardToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setUserLevel",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "usedNonces",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userLevel",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyAndReward",
    values: [
      string,
      boolean,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      AddressLike,
      BytesLike
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "BASE_REWARD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "COMMENT_WEIGHT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "COOLDOWN_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ENGAGEMENT_TYPEHASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ENGAGEMENT_WINDOW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LIKE_WEIGHT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_BONUS_MULTIPLIER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_REP_BONUS_PCT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_CONFIDENCE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SHARE_WEIGHT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VERDICT_TYPEHASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VIEW_WEIGHT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedVerifiers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchSetUserLevels",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimEngagementBonus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eip712Domain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPostReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastRewardTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "postRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setUserLevel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usedNonces", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "userLevel", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyAndReward",
    data: BytesLike
  ): Result;
}

export namespace BonusRewardMintedEvent {
  export type InputTuple = [
    postCid: string,
    wallet: AddressLike,
    bonusReward: BigNumberish,
    likes: BigNumberish,
    comments: BigNumberish,
    views: BigNumberish,
    shares: BigNumberish
  ];
  export type OutputTuple = [
    postCid: string,
    wallet: string,
    bonusReward: bigint,
    likes: bigint,
    comments: bigint,
    views: bigint,
    shares: bigint
  ];
  export interface OutputObject {
    postCid: string;
    wallet: string;
    bonusReward: bigint;
    likes: bigint;
    comments: bigint;
    views: bigint;
    shares: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EIP712DomainChangedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PostVerifiedEvent {
  export type InputTuple = [
    postCid: string,
    wallet: AddressLike,
    confidence: BigNumberish,
    baseReward: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    postCid: string,
    wallet: string,
    confidence: bigint,
    baseReward: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    postCid: string;
    wallet: string;
    confidence: bigint;
    baseReward: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerifierAddedEvent {
  export type InputTuple = [verifier: AddressLike];
  export type OutputTuple = [verifier: string];
  export interface OutputObject {
    verifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerifierRemovedEvent {
  export type InputTuple = [verifier: AddressLike];
  export type OutputTuple = [verifier: string];
  export interface OutputObject {
    verifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DynamicVerification extends BaseContract {
  connect(runner?: ContractRunner | null): DynamicVerification;
  waitForDeployment(): Promise<this>;

  interface: DynamicVerificationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BASE_REWARD: TypedContractMethod<[], [bigint], "view">;

  COMMENT_WEIGHT: TypedContractMethod<[], [bigint], "view">;

  COOLDOWN_PERIOD: TypedContractMethod<[], [bigint], "view">;

  ENGAGEMENT_TYPEHASH: TypedContractMethod<[], [string], "view">;

  ENGAGEMENT_WINDOW: TypedContractMethod<[], [bigint], "view">;

  LIKE_WEIGHT: TypedContractMethod<[], [bigint], "view">;

  MAX_BONUS_MULTIPLIER: TypedContractMethod<[], [bigint], "view">;

  MAX_REP_BONUS_PCT: TypedContractMethod<[], [bigint], "view">;

  MIN_CONFIDENCE: TypedContractMethod<[], [bigint], "view">;

  SHARE_WEIGHT: TypedContractMethod<[], [bigint], "view">;

  VERDICT_TYPEHASH: TypedContractMethod<[], [string], "view">;

  VIEW_WEIGHT: TypedContractMethod<[], [bigint], "view">;

  addVerifier: TypedContractMethod<[v: AddressLike], [void], "nonpayable">;

  authorizedVerifiers: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  batchSetUserLevels: TypedContractMethod<
    [users: AddressLike[], levels: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  claimEngagementBonus: TypedContractMethod<
    [
      postCid: string,
      likes: BigNumberish,
      comments: BigNumberish,
      views: BigNumberish,
      shares: BigNumberish,
      timestamp: BigNumberish,
      nonce: BigNumberish,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  eip712Domain: TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;

  getPostReward: TypedContractMethod<
    [postCid: string],
    [DynamicVerification.PostRewardStructOutput],
    "view"
  >;

  lastRewardTime: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  postRewards: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, bigint, bigint, boolean, boolean] & {
        author: string;
        baseRewardMinted: bigint;
        bonusRewardMinted: bigint;
        verifiedAt: bigint;
        bonusClaimedAt: bigint;
        verified: boolean;
        bonusClaimed: boolean;
      }
    ],
    "view"
  >;

  removeVerifier: TypedContractMethod<[v: AddressLike], [void], "nonpayable">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  rewardToken: TypedContractMethod<[], [string], "view">;

  setUserLevel: TypedContractMethod<
    [user: AddressLike, level: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  usedNonces: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  userLevel: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  verifyAndReward: TypedContractMethod<
    [
      postCid: string,
      isEco: boolean,
      confidence: BigNumberish,
      timestamp: BigNumberish,
      nonce: BigNumberish,
      wallet: AddressLike,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BASE_REWARD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "COMMENT_WEIGHT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "COOLDOWN_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ENGAGEMENT_TYPEHASH"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ENGAGEMENT_WINDOW"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LIKE_WEIGHT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_BONUS_MULTIPLIER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_REP_BONUS_PCT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_CONFIDENCE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SHARE_WEIGHT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VERDICT_TYPEHASH"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "VIEW_WEIGHT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addVerifier"
  ): TypedContractMethod<[v: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizedVerifiers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "batchSetUserLevels"
  ): TypedContractMethod<
    [users: AddressLike[], levels: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimEngagementBonus"
  ): TypedContractMethod<
    [
      postCid: string,
      likes: BigNumberish,
      comments: BigNumberish,
      views: BigNumberish,
      shares: BigNumberish,
      timestamp: BigNumberish,
      nonce: BigNumberish,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "eip712Domain"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPostReward"
  ): TypedContractMethod<
    [postCid: string],
    [DynamicVerification.PostRewardStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "lastRewardTime"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "postRewards"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, bigint, bigint, boolean, boolean] & {
        author: string;
        baseRewardMinted: bigint;
        bonusRewardMinted: bigint;
        verifiedAt: bigint;
        bonusClaimedAt: bigint;
        verified: boolean;
        bonusClaimed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "removeVerifier"
  ): TypedContractMethod<[v: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rewardToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setUserLevel"
  ): TypedContractMethod<
    [user: AddressLike, level: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usedNonces"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "userLevel"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "verifyAndReward"
  ): TypedContractMethod<
    [
      postCid: string,
      isEco: boolean,
      confidence: BigNumberish,
      timestamp: BigNumberish,
      nonce: BigNumberish,
      wallet: AddressLike,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "BonusRewardMinted"
  ): TypedContractEvent<
    BonusRewardMintedEvent.InputTuple,
    BonusRewardMintedEvent.OutputTuple,
    BonusRewardMintedEvent.OutputObject
  >;
  getEvent(
    key: "EIP712DomainChanged"
  ): TypedContractEvent<
    EIP712DomainChangedEvent.InputTuple,
    EIP712DomainChangedEvent.OutputTuple,
    EIP712DomainChangedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PostVerified"
  ): TypedContractEvent<
    PostVerifiedEvent.InputTuple,
    PostVerifiedEvent.OutputTuple,
    PostVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "VerifierAdded"
  ): TypedContractEvent<
    VerifierAddedEvent.InputTuple,
    VerifierAddedEvent.OutputTuple,
    VerifierAddedEvent.OutputObject
  >;
  getEvent(
    key: "VerifierRemoved"
  ): TypedContractEvent<
    VerifierRemovedEvent.InputTuple,
    VerifierRemovedEvent.OutputTuple,
    VerifierRemovedEvent.OutputObject
  >;

  filters: {
    "BonusRewardMinted(string,address,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      BonusRewardMintedEvent.InputTuple,
      BonusRewardMintedEvent.OutputTuple,
      BonusRewardMintedEvent.OutputObject
    >;
    BonusRewardMinted: TypedContractEvent<
      BonusRewardMintedEvent.InputTuple,
      BonusRewardMintedEvent.OutputTuple,
      BonusRewardMintedEvent.OutputObject
    >;

    "EIP712DomainChanged()": TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;
    EIP712DomainChanged: TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PostVerified(string,address,uint256,uint256,uint256)": TypedContractEvent<
      PostVerifiedEvent.InputTuple,
      PostVerifiedEvent.OutputTuple,
      PostVerifiedEvent.OutputObject
    >;
    PostVerified: TypedContractEvent<
      PostVerifiedEvent.InputTuple,
      PostVerifiedEvent.OutputTuple,
      PostVerifiedEvent.OutputObject
    >;

    "VerifierAdded(address)": TypedContractEvent<
      VerifierAddedEvent.InputTuple,
      VerifierAddedEvent.OutputTuple,
      VerifierAddedEvent.OutputObject
    >;
    VerifierAdded: TypedContractEvent<
      VerifierAddedEvent.InputTuple,
      VerifierAddedEvent.OutputTuple,
      VerifierAddedEvent.OutputObject
    >;

    "VerifierRemoved(address)": TypedContractEvent<
      VerifierRemovedEvent.InputTuple,
      VerifierRemovedEvent.OutputTuple,
      VerifierRemovedEvent.OutputObject
    >;
    VerifierRemoved: TypedContractEvent<
      VerifierRemovedEvent.InputTuple,
      VerifierRemovedEvent.OutputTuple,
      VerifierRemovedEvent.OutputObject
    >;
  };
}
