/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace EcoBoost {
  export type BoostStruct = {
    booster: AddressLike;
    level: BigNumberish;
    amount: BigNumberish;
    timestamp: BigNumberish;
  };

  export type BoostStructOutput = [
    booster: string,
    level: bigint,
    amount: bigint,
    timestamp: bigint
  ] & { booster: string; level: bigint; amount: bigint; timestamp: bigint };
}

export interface EcoBoostInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BURN_ADDRESS"
      | "FLAME_COST"
      | "SPARK_COST"
      | "WILDFIRE_COST"
      | "boostPost"
      | "boosts"
      | "ecoToken"
      | "getActiveBoostLevel"
      | "getBoostCount"
      | "getBoosts"
      | "owner"
      | "renounceOwnership"
      | "totalBoosts"
      | "totalBurned"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "OwnershipTransferred" | "PostBoosted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BURN_ADDRESS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FLAME_COST",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SPARK_COST",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "WILDFIRE_COST",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "boostPost",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "boosts",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "ecoToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getActiveBoostLevel",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getBoostCount",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "getBoosts", values: [string]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalBoosts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalBurned",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "BURN_ADDRESS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "FLAME_COST", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "SPARK_COST", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "WILDFIRE_COST",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "boostPost", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "boosts", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ecoToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getActiveBoostLevel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBoostCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBoosts", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalBoosts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalBurned",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PostBoostedEvent {
  export type InputTuple = [
    postCid: string,
    booster: AddressLike,
    level: BigNumberish,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    postCid: string,
    booster: string,
    level: bigint,
    amount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    postCid: string;
    booster: string;
    level: bigint;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EcoBoost extends BaseContract {
  connect(runner?: ContractRunner | null): EcoBoost;
  waitForDeployment(): Promise<this>;

  interface: EcoBoostInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BURN_ADDRESS: TypedContractMethod<[], [string], "view">;

  FLAME_COST: TypedContractMethod<[], [bigint], "view">;

  SPARK_COST: TypedContractMethod<[], [bigint], "view">;

  WILDFIRE_COST: TypedContractMethod<[], [bigint], "view">;

  boostPost: TypedContractMethod<
    [postCid: string, level: BigNumberish],
    [void],
    "nonpayable"
  >;

  boosts: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [string, bigint, bigint, bigint] & {
        booster: string;
        level: bigint;
        amount: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  ecoToken: TypedContractMethod<[], [string], "view">;

  getActiveBoostLevel: TypedContractMethod<[postCid: string], [bigint], "view">;

  getBoostCount: TypedContractMethod<[postCid: string], [bigint], "view">;

  getBoosts: TypedContractMethod<
    [postCid: string],
    [EcoBoost.BoostStructOutput[]],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  totalBoosts: TypedContractMethod<[], [bigint], "view">;

  totalBurned: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BURN_ADDRESS"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "FLAME_COST"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SPARK_COST"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "WILDFIRE_COST"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "boostPost"
  ): TypedContractMethod<
    [postCid: string, level: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "boosts"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [string, bigint, bigint, bigint] & {
        booster: string;
        level: bigint;
        amount: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "ecoToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getActiveBoostLevel"
  ): TypedContractMethod<[postCid: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "getBoostCount"
  ): TypedContractMethod<[postCid: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "getBoosts"
  ): TypedContractMethod<
    [postCid: string],
    [EcoBoost.BoostStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalBoosts"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalBurned"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PostBoosted"
  ): TypedContractEvent<
    PostBoostedEvent.InputTuple,
    PostBoostedEvent.OutputTuple,
    PostBoostedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PostBoosted(string,address,uint8,uint256,uint256)": TypedContractEvent<
      PostBoostedEvent.InputTuple,
      PostBoostedEvent.OutputTuple,
      PostBoostedEvent.OutputObject
    >;
    PostBoosted: TypedContractEvent<
      PostBoostedEvent.InputTuple,
      PostBoostedEvent.OutputTuple,
      PostBoostedEvent.OutputObject
    >;
  };
}
