/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ProfileRegistry } from "./ProfileRegistry";
export * as factories from "./factories";
export { ProfileRegistry__factory } from "./factories/ProfileRegistry__factory";
